name: pastor_report
description: A simple Flutter app for pastors to submit reports to different departments.

publish_to: 'none' # This prevents the package from being published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.6
  intl: ^0.19.0
  webview_flutter: ^4.0.0
  webview_flutter_android: ^3.16.7
  webview_flutter_wkwebview: ^3.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1 # Add the flutter_launcher_icons package

# Configuration for flutter_launcher_icons to generate app icons for Android and iOS
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Path to your main icon image (1024x1024 pixels recommended)

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Ensure your header image is placed here
